name: notebook
channels:
  - conda-forge

dependencies:
  # 1. Build tools needed to compile llama-cpp-python
  - cmake
  - ninja
  - gcc_linux-64
  - gxx_linux-64
  - cuda-toolkit=12.9
  - pip
  
  # 2. Your custom ML tools (No PyTorch here!)
  - pip:
      - transformers==4.46.3
      - openai>=1.0
      - anthropic>=0.8
      - python-dotenv
      - langchain>=0.1
      - sentence-transformers==3.4.1
      - otter-grader==6.1.6
      - huggingface_hub
      - gradio
      - docutils<0.20
      - onnxruntime
